export const CONFIG = {
  CACHE: {
    TTL_MS: 5000,
    MAX_SIZE: 50,
    ENABLED: true,
  },
  RATE_LIMIT: {
    CONTROL_COOLDOWN_MS: 200,
    MAX_REQUESTS: 10,
    WINDOW_MS: 1000,
  },
  VALIDATION: {
    MAX_SEARCH_LENGTH: 1000,
    MAX_SERVICE_ID_LENGTH: 256,
  },
  PERFORMANCE: {
    OPERATION_TIMEOUT_MS: 30000,
    MAX_CONCURRENT_OPS: 5,
  },
  WINDOW: {
    DEFAULT_WIDTH: 1200,
    DEFAULT_HEIGHT: 780,
    MIN_WIDTH: 960,
    MIN_HEIGHT: 600,
    BACKGROUND_COLOR: '#000000',
  },
  SECURITY: {
    AUDIT_ENABLED: true,
    STRICT_VALIDATION: true,
  },
} as const;
